blog/urls.py
from django.urls import path

from . import views
app_name = 'blog'

urlpatterns = [
    path('',views.all_blogs , name = 'all_blogs'),
    path('<int:blog_id>/',views.blog_detail ,name = 'blog_detail')
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home , name = 'home'),
    path('about/',views.about , name = 'about'),
    path('blogs/', include('blog.urls')),
    path('teams',views.team , name = 'team')
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()
    
    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class project(models.Model):
    title = models.CharField(max_length = 100)
    description = models.CharField(max_length=100)
    image = models.ImageField(upload_to = 'portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render , get_object_or_404
from .models import blog

def all_blogs(request):

    blogs = blog.objects.order_by('-date')
    return render(request , 'blog/all_blogs.html',{'blogs':blogs})


def blog_detail(request, blog_id) :
    all_blog = get_object_or_404(blog , pk=blog_id)
    return render(request,'blog/blog_details.html',{'all_blog':all_blog})

portfolio/views.py
from django.shortcuts import render
from .models import project

def home(request) :
    projects = project.objects.all()
    return render(request , 'portfolio/home.html', {'projects':projects})

def about(request):
    return render(request,'portfolio/about.html')

def team(request):
    projects = project.objects.all()
    return render(request,'portfolio/team.html', {'projects':projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}

<section class="container mt-5">
    <h1 class="text-center">Razzak has Written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h1>
    <div class="row row-cols-1 row-cols-md-3 g-4 mt-5 text-center">
        {% for blog in blogs %}
        <div class="col">
            <div class="card h-100">
                <a style="text-decoration: none;" href="{% url 'blog:blog_detail' blog.id %}"><h1>{{ blog.title }}</h1></a>
                <div class="card-body">
                <h5 class="card-title">{{ blog.date|date:'M d Y' }}</h5>
                <p class="card-text">{{ blog.description }}</p>
                </div>    
            </div>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

blog/templates/blog/blog_details.html
{% extends 'portfolio/base.html' %}

{% block content %}
<section class="container mt-5 ">
    <h1 class="text-center">WelCome To My Blog</h1>

    <div class="text-center mt-5 card h-100">
        <h1>{{ all_blog.title }}</h1>
        <div class="text-center">
            <h5 class="card-title">{{ all_blog.date}}</h5>
            <p class="card-text">{{ all_blog.description }}</p>
        </div>
    </div>
</section>
{% endblock %}

portfolio/templates/portfolio/about.html
{% extends 'portfolio/base.html' %}
{% block content %}
{% load static %}
<section class="container mt-5">
    <h1 class="text-center">About Me</h1>
    <div class="row p-3">
        <div class="col-md-6 mt-5">
            <img class="float-start rounded-3" src="{% static 'portfolio/243561821_1011273306114730_808639990406022995_n.jpg' %}" height="300" width="350" alt="">
        </div>
        <div class="col-md-6 mt-5">
            <h1 class="text-uppercase penguins">I Am Programmer</h1>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit.
            Necessitatibus veritatis quibusdam vero nemo nobis autem
            quisquam
            quas repellat facilis expedita quaerat explicabo illo porro,
            tempora, voluptatibus doloribus, ducimus esse. Accusamus?</p>
            <button class="btn btn-info text-white"><a style="text-decoration: none; color: white;" href="{% static 'portfolio/Abdur Razzak cv.pdf' %}">Download Resume</a></button>
        </div>

    </div>
</section>
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Abdur Razzak</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

    <link rel="icon" type="image/png" href="{% static 'portfolio/arlogo.png' %}">
  </head>
  <body>
    <header class="panda-header">
      <section class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container-fluid logo">
            <a class="navbar-brand"href="#"><img src="{% static 'portfolio/logo.png' %}" width="150" height="50" alt=""><br></a>
            <button class="navbar-toggler" type="button"
              data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
              aria-controls="navbarNavAltMarkup" aria-expanded="false"
              aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse nav justify-content-end"
              id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                <a class="nav-link active" href="{% url 'about' %}">About Me</a>
                <a class="nav-link active" href="{% url 'blog:all_blogs' %}">Blogs</a>
                <a class="nav-link active" href="{% url 'team' %}">My Teams</a>

              </div>
            </div>
          </div>
        </nav>
      </section>
    </header>
    {% block content %}{% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content %}
{% load static %}
<section class="container mt-5">
    <div class="row p-3 razzak-home">
        <div class="col-md-6 mt-5 razzak-left">
            <h1 class="text-uppercase Port">Md. Abdur Razzak<br><span>Web
                    Developer</span></h1>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                Necessitatibus veritatis quibusdam vero nemo nobis autem
                quisquam
                quas repellat facilis expedita quaerat explicabo illo porro,
                tempora, voluptatibus doloribus, ducimus esse. Accusamus?</p>
            <button class="btn btn-info text-white"><a style="text-decoration: none;color: tomato" href="{% static 'portfolio/razzak.html' %}">Hire Me</a></button>

        </div>
        <div class="col-md-6 bg-image razzak-right">
            <img class="float-end" src="{% static 'portfolio/razzak.png' %}"
                height="450"
                width="450" alt="">
        </div>
 
    </div>
</section>
<section class="container mt-5">
    <h1 class="text-center">About Me</h1>
    <div class="row p-3">
        <div class="col-md-6 mt-5">
            <img class="float-start rounded-3" src="{% static 'portfolio/243561821_1011273306114730_808639990406022995_n.jpg' %}" height="300" width="350" alt="">
        </div>
        <div class="col-md-6 mt-5">
            <h1 class="text-uppercase penguins">I Am Programmer</h1>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit.
            Necessitatibus veritatis quibusdam vero nemo nobis autem
            quisquam
            quas repellat facilis expedita quaerat explicabo illo porro,
            tempora, voluptatibus doloribus, ducimus esse. Accusamus?</p>
            <button class="btn btn-info text-white"><a style="text-decoration: none; color: white;" href="{% static 'portfolio/Abdur Razzak cv.pdf' %}">Download Resume</a></button>
        </div>

    </div>
</section>

<section class="container mt-5">
    <h1 class="text-center">My Teams </h1>
    <div class="row row-cols-1 row-cols-md-3 g-4 mt-5">
        {% for project in projects %}
        <div class="col">
            <div class="card h-100">
                <img style="border-radius: 100%;" src="{{ project.image.url }}" height="300" class="card-img-top p-sm-5"  >
                <div class="card-body">
                <h5 class="card-title">{{ project.title }}</h5>
                <p class="card-text">{{ project.description }}</p>
                {% if project.url %}
                <h6><a style="text-decoration: none;color: tomato" href="{{ project.url }}">Show Details...</a></h6>
                {% endif %}
                </div>    
            </div>
        </div>
        {% endfor %}
    </div>
</section>
<section class="container mt-5 bg-dark">
    <footer class=" text-center text-white">
        <p>Design And Develop By Abdur Razzak</p>

    </footer>
</section>
{% endblock %}

Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam non nulla ut dolorem magni laudantium exercitationem excepturi quo eum nesciunt quos fuga ratione, voluptates cupiditate ab provident consequuntur ullam animi?

portfolio/templates/portfolio/team.html
{% extends 'portfolio/base.html' %}
{% block content %}
{% load static %}
<section class="container mt-5">
    <h1 class="text-center">My Teams </h1>
    <div class="row row-cols-1 row-cols-md-3 g-4 mt-5">
        {% for project in projects %}
        <div class="col">
            <div class="card h-100">
                <img style="border-radius: 100%;" src="{{ project.image.url }}" height="300" class="card-img-top p-sm-5"  >
                <div class="card-body">
                <h5 class="card-title">{{ project.title }}</h5>
                <p class="card-text">{{ project.description }}</p>
                {% if project.url %}
                <h6><a style="text-decoration: none;color: tomato;" href="{{ project.url }}">Show Details...</a></h6>
                {% endif %}
                </div>    
            </div>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}